In [3]:
import pandas as p 

data = p.read_csv("thanksgiving.csv",encoding="Latin-1")
data.head()

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific

In [4]:
data["Do you celebrate Thanksgiving?"].value_counts()

Yes    980
No      78
Name: Do you celebrate Thanksgiving?, dtype: int64

In [5]:
data=data[data["Do you celebrate Thanksgiving?"]=='Yes']

In [6]:
data["What is typically the main dish at your Thanksgiving dinner?"].value_counts()

Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
I don't know                5
Turducken                   3
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

In [7]:
data[data["What is typically the main dish at your Thanksgiving dinner?"] =="Tofurkey"]["Do you typically have gravy?"]

4      Yes
33     Yes
69      No
72      No
77     Yes
145    Yes
175    Yes
218     No
243    Yes
275     No
393    Yes
399    Yes
571    Yes
594    Yes
628     No
774     No
820     No
837    Yes
860     No
953    Yes
Name: Do you typically have gravy?, dtype: object

In [44]:
data[data["What is typically the main dish at your Thanksgiving dinner?"]=="Tofurkey"]

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region,int_age,int_income
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific,30.0,100000.0
33,4337771439,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,NaN,Suburban,30 - 44,Male,"$50,000 to $74,999",Middle Atlantic,30.0,50000.0
69,4337553422,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,NaN,Urban,18 - 29,Male,"$10,000 to $24,999",West South Central,18.0,10000.0
72,4337540484,Yes,Tofurkey,NaN,I don't know,NaN,Bread-based,NaN,None,NaN,...,Yes,No,NaN,Suburban,18 - 29,Male,Prefer not to answer,Pacific,18.0,NaN
77,4337490067,Yes,Tofurkey,NaN,Roasted,NaN,None,NaN,None,NaN,...,No,No,NaN,Urban,30 - 44,Male,Prefer not to answer,East North Central,30.0,NaN
145,4337191550,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,NaN,Urban,30 - 44,Female,"$125,000 to $149,999",West South Central,30.0,125000.0
175,4337139327,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,NaN,Rural,30 - 44,Female,"$75,000 to $99,999",West North Central,30.0,75000.0
218,4337078951,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,NaN,Suburban,30 - 44,Female,"$200,000 and up",Mountain,30.0,200000.0
243,4337044348,Yes,Tofurkey,NaN,Other (please specify),various ways,Bread-based,NaN,Canned,NaN,...,No,No,NaN,Urban,60+,Female,"$100,000 to $124,999",South Atlantic,60.0,100000.0
275,4336997445,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Middle Atlantic,30.0,100000.0
393,4336894719,Yes,Tofurkey,NaN,Roasted,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,NaN,Rural,18 - 29,Female,"$25,000 to $49,999",New England,18.0,25000.0
399,4336891075,Yes,Tofurkey,NaN,Roasted,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,NaN,Suburban,60+,Female,"$125,000 to $149,999",South Atlantic,60.0,125000.0
571,4336760110,Yes,Tofurkey,NaN,Roasted,NaN,Bread-based,NaN,None,NaN,...,No,No,NaN,Suburban,18 - 29,Female,Prefer not to answer,South Atlantic,18.0,NaN
594,4336736562,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,No,No,NaN,Rural,45 - 59,Female,"$175,000 to $199,999",Middle Atlantic,45.0,175000.0
628,4336692873,Yes,Tofurkey,NaN,Baked,NaN,None,NaN,Homemade,NaN,...,Yes,No,NaN,Suburban,60+,Female,"$25,000 to $49,999",Middle Atlantic,60.0,25000.0
774,4336400854,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,Yes,Yes,Suburban,45 - 59,Female,"$75,000 to $99,999",Mountain,45.0,75000.0
820,4336238126,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,NaN,Urban,18 - 29,Female,"$10,000 to $24,999",Pacific,18.0,10000.0
837,4336175740,Yes,Tofurkey,NaN,Baked,NaN,None,NaN,None,NaN,...,Yes,Yes,No,Suburban,18 - 29,Female,"$25,000 to $49,999",West North Central,18.0,25000.0
860,4336121663,Yes,Tofurkey,NaN,Baked,NaN,Rice-based,NaN,Other (please specify),freshly made at a deli counter,...,No,No,NaN,Urban,30 - 44,Female,"$25,000 to $49,999",Pacific,30.0,25000.0
953,4336005220,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,NaN,Suburban,30 - 44,Male,"$0 to $9,999",Middle Atlantic,30.0,0.0

In [9]:
data["Do you typically have gravy?"]

0       Yes
1       Yes
2       Yes
3       Yes
4       Yes
5       Yes
6       Yes
7       Yes
8       Yes
9       Yes
11       No
12      Yes
13      Yes
14      Yes
15      Yes
16      Yes
17      Yes
18      Yes
19      Yes
20      Yes
21      Yes
23      Yes
24      Yes
25      Yes
26      Yes
27      Yes
28      Yes
29      Yes
30      Yes
32      Yes
       ...
1024     No
1025    Yes
1026    Yes
1027    Yes
1029    Yes
1030    Yes
1031    Yes
1033    Yes
1034    Yes
1035    Yes
1037     No
1038    Yes
1039    Yes
1040    Yes
1041    Yes
1042    Yes
1043    Yes
1044    Yes
1045    Yes
1046    Yes
1047    Yes
1048     No
1049    Yes
1050    Yes
1051    Yes
1053    Yes
1054    Yes
1055     No
1056    Yes
1057    Yes
Name: Do you typically have gravy?, dtype: object

In [13]:
apple_isnull=p.isnull(data["Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple"])
apple_isnull.value_counts()

False    514
True     466
Name: Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple, dtype: int64

In [12]:
pumpkin_isnull=p.isnull(data["Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin"])

pumpkin_isnull.value_counts()

False    729
True     251
Name: Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin, dtype: int64

In [15]:
pecan_isnull=p.isnull(data["Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan"])
pecan_isnull.value_counts()

True     638
False    342
Name: Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan, dtype: int64

In [24]:
ate_pies = apple_isnull & pumpkin_isnull & pecan_isnull
ate_pies.value_counts()

string = "Helc - okf"

print(string.split('-')[0].strip()+ "qohoo")

Helcqohoo

In [30]:
def conv_int (value):
    if p.isnull(value):
        return None
    elif len(value)==3:
        return int(60)
    else:
        return int(value.split('-')[0].strip())
data["int_age"] = data["Age"].apply(conv_int)

data["int_age"].describe()

abf

# Journey so far 

- As the age was provided in range, so for calculation purpose derived the age as the lower limit

### Pandas.Series.describe() 

Generates descriptive statistics that summarize the central tendency, dispersion and shape of a datasetâ€™s distribution, excluding NaN values.
Analyzes both numeric and object series, as well as DataFrame column sets of mixed data types. The output will vary depending on what is provided. Refer to the notes below for more detail

### Pandas.Series.apply()

Invoke function on values of Series. Can be ufunc (a NumPy function that applies to the entire Series) or a Python function that only works on single values. Can apply the function on the entire row

### Pandas.Series.value_counts()

Groups by the distinct values and returns the values with total counts

### Pandas.Series.isnull()

Returns a boolean series which has value True if the respective value in the column is null 

### Pandas.dataFrame.head()

Returns the first 5 rows of the dataframe

In [36]:
def convert_money(value):
    if p.isnull(value):
        return None
    elif "and" in value:
        return int(value.split("and")[0].replace('$','').replace(',','').strip())
    elif "$" in value:
        return int(value.split("to")[0].replace('$','').replace(',','').strip())
    else:
        return None

data["int_income"]=data["How much total combined money did all members of your HOUSEHOLD earn last year?"].apply(convert_money)

print(type(data["int_income"].describe()))

<class 'pandas.core.series.Series'>

### Findings
Although we only have a rough approximation of income, and it skews downward because we took the first value in each string (the lower bound), the average income seems to be fairly high, although there is also a large standard deviation.

In [58]:
not_rich=data[data["int_income"]<150000]["How far will you travel for Thanksgiving?"].value_counts()
print(not_rich)
rich =data[data["int_income"]>150000]["How far will you travel for Thanksgiving?"].value_counts()
print(rich)

Thanksgiving is happening at my home--I won't travel at all                         281
Thanksgiving is local--it will take place in the town I live in                     203
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    150
Thanksgiving is out of town and far away--I have to drive several hours or fly       55
Name: How far will you travel for Thanksgiving?, dtype: int64
Thanksgiving is happening at my home--I won't travel at all                         49
Thanksgiving is local--it will take place in the town I live in                     25
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    16
Thanksgiving is out of town and far away--I have to drive several hours or fly      12
Name: How far will you travel for Thanksgiving?, dtype: int64

### Findings
It appears that more people with high income have Thanksgiving at home than people with low income. This may be because younger students, who don't have a high income, tend to go home, whereas parents, who have higher incomes, don't.

In [59]:
data.pivot_table(
    index="Have you ever tried to meet up with hometown friends on Thanksgiving night?", 
    columns='Have you ever attended a "Friendsgiving?"',
    values="int_age"
)

Have you ever attended a "Friendsgiving?"                  No        Yes
Have you ever tried to meet up with hometown fr...
No                                                  42.283702  37.010526
Yes                                                 41.475410  33.976744

In [60]:
data.pivot_table(
    index="Have you ever tried to meet up with hometown friends on Thanksgiving night?", 
    columns='Have you ever attended a "Friendsgiving?"',
    values="int_income"
)

Have you ever attended a "Friendsgiving?"                     No           Yes
Have you ever tried to meet up with hometown fr...
No                                                  78914.549654  72894.736842
Yes                                                 78750.000000  66019.736842

### Findings
It appears that people who are younger are more likely to attend a Friendsgiving, and try to meet up with friends on Thanksgiving.

#### DataFrame.pivot_table(values=None, index=None, columns=None, aggfunc='mean') 
To create a group by subset over the selected columns and apply the aggregate functions on the respective values of some other column